---
services:
  gateway:
    image: acernei/gateway
    container_name: gateway
    environment:
      - "SD_URL=http://service-discovery:5001"
    ports:
      - 8080:8080

  service-discovery:
    image: acernei/service-discovery
    container_name: service-discovery
    ports:
      - 8081:5001
    depends_on:
      - gateway

  workout1:
    image: acernei/workout
    container_name: workout1
    environment:
      - "Kestrel__Endpoints__gRPC__Url=http://workout1:8082"
      - "ServiceDiscoveryUrl=http://service-discovery:5001"
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      - gateway
      - service-discovery
